# Crank Nicolson method

### Heat equation: metal heated in the middle

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [6]:
# Steps:

h = 0.025
k = 0.025

# Time and Space Vectors
x = np.arange(0, 1 + h, h)

t = np.arange(0, 0.1 + k, k)

print(len(x)) # Matrices should n-2 x n-2 = 39x39 

41


In [7]:
# Boundary conditions

bcs = [0, 0]

# Initial conditions

ics = np.sin(np.pi*x)


In [8]:
# Matrix for temperatures

n = len(x)
m = len(t)

T = np.zeros((n,m))

print(T.shape)

(41, 5)


In [12]:
# Add the bcs:

T[0, :] = bcs[0]

T[-1, :] = bcs[1]


# Add the ics

T[:, 0] = ics

#print(T)

In [15]:
c_2 = 1

r_factor = c_2*k/h**2

print(r_factor)

39.99999999999999


## First matrix:

In [19]:
D1_matrix_0 = np.diag([2 + 2*r_factor]*(n - 2), 0)

D1_matrix_n = np.diag([-r_factor]*(n - 3), -1)

D1_matrix_p = np.diag([-r_factor]*(n - 3), +1)

D1_matrix   = D1_matrix_0 + D1_matrix_n + D1_matrix_p

print(D1_matrix)
print(D1_matrix.shape)

[[ 82. -40.   0. ...   0.   0.   0.]
 [-40.  82. -40. ...   0.   0.   0.]
 [  0. -40.  82. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...  82. -40.   0.]
 [  0.   0.   0. ... -40.  82. -40.]
 [  0.   0.   0. ...   0. -40.  82.]]
(39, 39)


## Second matrix:

In [20]:
D2_matrix_0 = np.diag([2 - 2*r_factor]*(n - 2), 0)

D2_matrix_n = np.diag([r_factor]*(n - 3), -1)

D2_matrix_p = np.diag([r_factor]*(n - 3), +1)

D2_matrix   = D2_matrix_0 + D2_matrix_n + D2_matrix_p

print(D2_matrix)
print(D2_matrix.shape)

[[-78.  40.   0. ...   0.   0.   0.]
 [ 40. -78.  40. ...   0.   0.   0.]
 [  0.  40. -78. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ... -78.  40.   0.]
 [  0.   0.   0. ...  40. -78.  40.]
 [  0.   0.   0. ...   0.  40. -78.]]
(39, 39)


### The b vector, vector of known values

In [26]:
for j in range(0, m-1):
    
    b = T[1:-1, j].copy()
    #print(b.shape)
    #print(b)
    
    b = np.dot(D2_matrix, b)
    
    # Append missing values
    
    b[0]  = b[0]  + r_factor*(T[0, j+1] + T[0, j])
    b[-1] = b[-1] + r_factor*(T[-1, j+1] + T[-1, j])
    
    